name: influxdb 
version: 0.9.6.1-1
# The vendor for the snap (replace 'Vendor <email@example.com>')
vendor: Woodrow Shen <woodrow.shen@canonical.com>
summary: An Open-Source, Distributed, Time Series Database
description: InfluxDB is an open source distributed time series database with no external dependencies. It's useful for recording metrics, events, and performing analytics.
icon: influxdb.jpg 
services:
  webserver:
    description: Influxdb service
    start: bin/start-service.sh
    ports:
      external:
        ui:
          port: 8083/tcp
          negotiable: no
    security-override:
      seccomp: meta/influxdb.filter
      apparmor: meta/influxdb.apparmor
parts:
  influxdb:
    plugin: make
    source: . 
