name: woodrow-influxdb
version: 1.4.0-1
summary: An Open-Source Time Series Database
description: |
  InfluxDB is an open source time series database with no external dependencies. 
  It's useful for recording metrics, events, and performing analytics.
confinement: strict
grade: stable

apps:
  influxdb:
    command: bin/influxd-internal
    plugs:
      - network
      - network-bind
    daemon: simple

parts:
  influxdb-bin:
    plugin: dump
    source: bin
    organize:
      influxd-internal: bin/
  influxdb-etc:
    plugin: dump
    source: etc/influxdb
    organize:
      influxdb.conf: etc/influxdb/influxdb.conf
  influxdb-common:
    plugin: dump
    source: .
    organize:
      types.db: usr/share/collectd/types.db
  influxdb:
    plugin: make
    source: .
    after: [go]
  go: 
    source-tag: go1.8.3
